
**Notas complementarias a las transparencias**

* 14/09/2022 
    * Se ha introducido en las listas el ejemplo l=3*[1]
    * Se ha completado el ejemplo de *dictionary comprenhesion* 
    * Se ha completado el ejemplo del uso de args kwargs en las funciones|

# Tipos de datos


* Dos tipos generales de datos:
    * Escalares:int,float,complex,bool,str
    * Contenedores (tipos estructurados):contienen un número arbitrario de de escalares o de otros contenedores
* En Python todo son objetos, por tanto también lo son todos los tipos de datos 

In [124]:
b = 3 # entero
a = [1, 2, 3]  # lista en la que sus elementos son enteros
c = [ [1,2], "hola" ]  #lista en la que su primer elemento es una lista y el segundo una cadena de caracteres
d = (1, 2, 3) # tupla de enteros
e = { 'name' : "Fulano", 'last_name' : 'Perez', 'edad' : 18} # Diccionario

* A diferencia de C las variables de Python no están fuertemente tipadas. Los tipos se asignan de forma implícita y se comprueban en tiempo de ejecución

* Se puede comprobar de forma explicita el tipo, clase, de un objeto con las funciones `type()` y `ìsinstance()` 

In [125]:
type(a)   # Comprobamos el tipo del objeto a

list

In [126]:
isinstance (a, list) # Preguntamos si el objeto a es una instancia de la clase list

True

In [127]:
type(a) is list # utilizamos el operador is

True

**Importantísimo**. 

   * El concepto de variable en Python es radicalmente diferente al de C. En Python una variable debe entenderse como un enlace a un objeto. 
   * Todo objeto tiene un identificador. El identificador es único para cada objeto.  Con la función `ìd()` podemos acceder al identificador del objeto 
   * En Python hay objetos que son mutables y otros que son no-mutables o inmutables. Los objetos mutables se pueden modificar, los no-mutables no. Por ejemplo, los enteros son objetos no mutables mientras que las listas son objetos mutables.

   En el siguiente código de [pythontutor](https://pythontutor.com/) es importantísimo que entiendas porque hay variables que tiene id iguales o por qué cuando "aparentemente se modifican" las variables, algunas veces cambian su id pero en otras no. Para ello debes entender (i) la diferencia entre el objeto en sí y el enlace al objeto y (ii) la diferencia entre modificar un objeto y enlazar un nuevo objeto. **Si tienes dificultades pregunta pero no podrás programar en Python sino lo entiendes.**  
[codigo](https://pythontutor.com/visualize.html#code=int_a%20%3D%203%0Aint_b%20%3D%20int_a%0A%0Aprint%28int_a,%20int_b%29%0Aprint%28id%28int_a%29,%20id%28int_b%29%29%0A%0A%23%20Modify%20the%20int%0Aint_a%20%2B%3D%201%0Aprint%28int_a,%20int_b%29%0Aprint%28id%28int_a%29,%20id%28int_b%29%29%0A%0A%0Al_a%20%3D%20%5B1,%202,%203%5D%20%0Al_b%20%3D%20l_a%0Al_c%20%3D%20%5B1,%202,%203%5D%0A%0Aprint%20%28l_a,%20l_b,%20l_c%29%0Aprint%28id%28l_a%29,%20id%28l_b%29,%20id%28l_c%29%29%0A%0A%23%20modify%20the%20list%0Al_a%5B0%5D%20%3D%20%5B4,5,6%5D%0Al_a%5B1%5D%20%3D%20%7B'name'%3A'fulano',%20'edad'%3A3%7D%0Aprint%20%28l_a,%20l_b,%20l_c%29%0Aprint%28id%28l_a%29,%20id%28l_b%29,%20id%28l_c%29%29%0A%0As_a%20%3D%20%22Hello%20world%22%20%20%23objeto%20inmutable%0As_b%20%3D%20s_a%0As_c%20%3D%20%22Hello%20world%22%0Aprint%28id%28s_a%29,%20id%28s_b%29,%20id%28s_c%29%20%29%0A%0A%0Aprint%28%20id%28l_a%5B1%5D%5B'edad'%5D%29%20%29&cumulative=false&heapPrimitives=nevernest&mode=edit&origin=opt-frontend.js&py=3&rawInputLstJSON=%5B%5D&textReferences=false)

* En Python es fácil intercambiar valores de variables. ¿Entiendes por qué? 

In [128]:
a = 3
b = [1, 2,3]
print (a, b)

a,b = b, a
print(a, b)

3 [1, 2, 3]
[1, 2, 3] 3


# Tipos estructurados

Python tiene cinco tipos estructurados: cadenas (`strings`), tuplas (`tuples`), listas (`lists`), diccionarios (`dicts`) y conjuntos (`sets`)

## String (cadenas)

* Son secuencias ordenadas de caracteres delimitadas por comillas simples, comillas dobles o triples


In [1]:
a = 'esto es una cadena con el caracter 3'
b = """esto es otra cadena 
en dos lineas"""
c = "ESTO ES OTRA CADENA"
print(a)
print(b)

esto es una cadena con el caracter 3
esto es otra cadena 
en dos lineas


* Las cadenas de caracteres son **objetos ordenables**. Por tanto sus elementos (caracteres) son accesibles mediante un índice. 

In [130]:
print( a[0] ) # accede al primer caracter
print( a[-1] ) # accede al ultimo caracter

e
3


* Las cadenas son objetos **inmutables**. Una vez creado un objeto inmutable no se puede modificar. El siguiente código lanza una excepción de la clase `TypeError` cuando se intenta modificar la cadena de caracteres

In [131]:
a[0] = 3

TypeError: 'str' object does not support item assignment

* Las cadenas son objetos **iterables**, i.e., sus elementos se pueden iterar en un bucle

In [132]:
a = "Hello World"

# Iterando sobre la cadena
for x in a:
    print(x)

H
e
l
l
o
 
W
o
r
l
d


### Operadores

|Operator |	Operation	| Description |
|-------- | ------------ | ----------- |
|Assignament|	s1 = s2 |	Link s2 to the object linked by s1. |
|Concatenation|	s1 + s2 |	Creates a new string concatenating two strings, s1 and s2. |
|Repetition |	s * n	| Makes n copies of string, s.|
|Indexing	| s [ i ] |	Indexing a string, returning element at index i. |
|Slicing |	s[ i : j : stride] 	| Slicing a string from i to j with an optional stride.|
|Membership |	x in s |	Returns True if the element, x is in the string, s. Otherwise False.|
||x not in s | 	Returns True if the element, x is not in the string, x. Otherwise False.|
|Comparison |	s1 == s2 | 	Returns True if string, s1 is the same as string, s2. Otherwise False.|
 || s1 != s2 | 	Returns True if string, s1 is not the same as string, s2. Otherwise False.|

* Algunos ejemplos de operadores que admiten las cadenas de caracteres

In [9]:
str1 = "esto "
str2 = "aa" 

strc = str1 + str2 # concatenación
print (strc)

esto aa


In [10]:
a,b = str2  #assignment with unpacking is allowed when the object is iterable
print(a)
print(b)

a
a


In [11]:
print ( str1 > str2)
print (str1 * 3) # repetition 
print ('es' in str1) # membership

True
esto esto esto 
True


* Se pueden acceder a *trozos* de una cadena

In [12]:
a = "Hello World"

print( a[:4]) # accede a los cuatro primeros caracteres
print( a[1:4])
print( a[::2] ) # accede a los caracteres que ocupan las posiciones impares
print( a[::-1]) # reversing string
print( a[-3:])  # accede a los ultimos 3 elementos 

Hell
ell
HloWrd
dlroW olleH
rld


### Algunos métodos para manejar cadenas

* Rara acceder a los métodos de cualquier objeto '`a` se puede utilizar el tabulador o la función `dir()` o `a. + tab` 

In [139]:
a = "cadena con un 3"
dir(a)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isascii',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'strip',
 'swapcase',
 'title',
 'translate',
 'upper',


* Algunos ejemplos de métodos de cadenas de caracteres

In [140]:
a.upper() # Devuelve una cadena con la versión en mayúsculas del objeto a.

'CADENA CON UN 3'

In [141]:
# También es válido
"cadena con un 3".upper()

'CADENA CON UN 3'

In [142]:
print( a.isdigit() ) #Comprueba si todos los caracteres del objeto a son dígitos

False


In [13]:
a[-1].isdigit()   # Comprueba si el último elemento de la cadena a es un dígito

False

In [144]:
a[:4].isalpha()  # comprueba si los 4 primeros caracteres de la cadena son símlos del alfabeto

True

In [14]:
string = 'con'
a.find (string) # busca la cadena string en a devolviendo el primer índice donde empieza o -1 si no se ha encontrado

-1

In [146]:
print(a)
separator = 'a'
a.split (separator) # devuelve una lista de subcadenas separadas por el separador indicado

cadena con un 3


['c', 'den', ' con un 3']

In [15]:
a.split()  # sino se le pasa argumento al método, se asume el blanco como separador

['Hello', 'World']

* El método `join` concatena las cadenas incluidas en la lista `sequence`. En la concatenación utiliza como separador la cadena `separator`.

In [147]:
separator = 'XXX'
separator.join( ['est0', 'es', 'una', 'cadena'] )

'est0XXXesXXXunaXXXcadena'

### Algo mas...

* Puedes utilizar el constructor `str()`para *convertir* un objeto en un string. El resultado dependerá de la implementación que haga el objeto que deseas convertir del método `__str__` . En el siguiente ejemplo vamos a convertir el entero 127 a un string y después comprobaremos el tipo del *nuevo* objeto.

In [5]:
a = 127
print(type(a))
print(id(a))


# a enlaza ahora con un nuevo objeto -> la cadena de caracteres 127.  
a = str(a)
print(type(a))
print(id(a))

<class 'int'>
94049803002592
<class 'str'>
140510128120048


Deberíamos haber sido mas rigurosos con nuestro lenguaje. En el código anterior **no** hemos convertido un entero en una cadena, hemos creado un nuevo objeto de la clase cadena de caracteres. En el siguiente ejemplo creamos una cadena a partir de una lista

In [19]:
l = [1, 2,3]
type(l)

list

In [150]:
a = str(l)
type(a)

str

¿Qué hace exactamente la función `str()`? Como hemos dicho, ejecuta el método `__str__` del objeto del cual queremos crear la cadena de caracteres. Por ejemplo la sentencia `a = str(l)` es equivalente a

In [20]:
# Enlazo b con el resultado de ejecutar el método __str__() de la lista l
b = l.__str__()
type(b)

str

## Listas

Secuencia mutable, ordenada e iterable de valores (posiblemente de diferentes tipos). Por tanto:
* sus elementos son accesible mediante un índice.
* se pueden obtener *trozos* de una lista
* se puede iterar para obtener sus elementos

In [23]:
l = ["Hello world", 1, 2, [3,4] ]
print(l)     #imprimo l lista
print (l[0]) # imprimo el primer elemento de la lista
print (l[-1]) # imprimo el ultimo elemento de la lista
print (l[:3]) # imprimo los tres primeros elementos de la lista

['Hello world', 1, 2, [3, 4]]
Hello world
[3, 4]
['Hello world', 1, 2]


 * Las listas son objetos iterables (implementan el método `__iter__`) y por tanto pueden iterarse en un bucle

In [153]:
for item in l:
    print (item)

Hello world
1
2
[3, 4]


* Las Listas se pueden concatenar ( + )

In [24]:
l3 = ["Bye"] 
l = l[:2] +  l3
l

['Hello world', 1, 'Bye']

* `l =[ ]` crea una lista vacía. Es equivalente a `l = list()`

* `len(obj)` devuelve el número de elementos en la lista `obj` . La función *len* cuando se invoca sobre un objeto *ejecuta* el método `__len__` de dicho objeto. 
* El operador `*` aplicado a una lista concatena la lista tantas veces como se indique en el coeficiente   

In [22]:
l = 3*[1,2]     # crea una lista concatenando 3 veces la lista [1,2]
print (len(l))
l

6


[1, 2, 1, 2, 1, 2]

* La función `list(a)` crea una lista a partir del objeto a iterable

In [26]:
a = "cadena"  # cadena
list (a)

['c', 'a', 'd', 'e', 'n', 'a']

In [28]:
d = { 'nombre':'Eduardo', 'edad':27}  # diccionario
list (d)

['nombre', 'edad']

* Cuando `list()`no reciba ningún argumento creará una lista vacía 

In [34]:
list()

[]

* Las listas se pueden *desempaquetar*

In [29]:
x, y, z = ["Hello", 'World', [1,2,3]]
print(x, y, z)

Hello World [1, 2, 3]


* Las listas están implementadas en C como arrays dinámicos
    * Añadir o eliminar elementos al final de la lista es rápido
    * No tanto en otras posiciones
    * Es una estructura de datos eficiente para pilas (pero no para colas)

### list comprenhesion: 

Es una manera concisa, y muy utilizada, de crear listas a partir de un objeto iterable

In [31]:
l = [2*n for n in range(10) ]  # range(n) crea una secuencia iterable con los n elementos: 0,1, ... (n-1)
l

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

* Muchas veces se utiliza **_comprenhesion_** junto con **_unpacking_**. 

Supón que tienes una lista cuyos elementos son tuplas y se desea crear otra lista cuyos elementos sean la suma de los elementos de las tuplas. Una forma de hacerlo sería:

In [157]:
l = [(1,2), (3,4), (5,6)] # lista cuyos elementos son tuplas

lc = [ x[0] + x[1] for x in l ]
print (lc)

[3, 7, 11]


Pero habitualmente verás el siguiente código que utiliza **unpacking**

In [158]:
l = [(1,2), (3,4), (5,6)] # lista cuyos elementos son tuplas

# Cada iteración devuelve una tupla de la lista. La tupla se despaqueta
# asignando a x e y los valores de la tupla
lc = [x+y for x, y in l]
print (lc)

[3, 7, 11]


Lo que **nunca** deberías hacer:

In [159]:
# Este código no deberáis utilizarlo, aunque produzca los resultados deseados
l = [(1,2), (3,4), (5,6)] # lista cuyos elementos son tuplas

lc = []
for x in l:
    lc.append (x[0]+x[1])
print(lc)

[3, 7, 11]


* Es muy habitual utilizar *list comprenhesion con condiciones* o *list comprenhesion con condicionales* (no son los mismo debes apreciar las diferencias entre ambas)

In [32]:
# list comprension with condition
l = [ 2*n for n in range(10) if n % 2 == 0]
l

[0, 4, 8, 12, 16]

In [33]:
# list comprenhension with conditionals

l = [ 'par' if n%2==0 else 'tres' if n==3 else 'impar' for n in range(10) ]
l

['par', 'impar', 'par', 'tres', 'par', 'impar', 'par', 'impar', 'par', 'impar']

### Función zip (e introducción a iteradores)

La función `zip()` devuelve un `iterador` de tuplas. Un iterador es un objeto que permite recorrer uno a uno sus elementos, para, eventualmente, operar con ellos. Un objetos que sea iterador debe implementar el método `next()`

* Los parámetros que se le pasen a la función `zip()` deben ser obejetos iterables. 
* Sino le pasases ningún parámetro, `zip()` devuelve un iterador vacío
* Si se le pasa un único prámetro, `zip()` devuelve un iterador de tuplas, donde cada tupla tendrña un único elemento.
* If multiple iterables are passed, `zip()` returns an iterator of tuples with each tuple having elements from all the iterables.

* Suppose, two iterables are passed to `zip()`; one iterable containing three and other containing five elements. Then, the returned iterator will contain three tuples. It's because the iterator stops when the shortest iterable is exhausted.


In [36]:
l1 = ['C', 'Python', 'JavaScript'] 
l2 = [17, 30, 40]
l3 = ['first', 'second', 'third', 'four']

# Creamos el iterador con la función zip pasándole como argumento tres listas
z = zip(l1, l2, l3) 
z

* Una vez creado el iterador, la función next nos permite iterar el iterador obteniendo uno a uno sus objetos.

In [37]:
print( next(z) )
print( next(z) )
print( next(z) )

('C', 17, 'first')
('Python', 30, 'second')
('JavaScript', 40, 'third')


El objeto devueltos en cada iteración del iterador `z` es una tupla con los correspondientes elementos de los parámetros con las que se creo `z`, en este caso tres listas. La primera vez que iteramos obtenemos  una tupla formada por los tres _primeros_ elementos de las tres listas. La segunda vez con los tres _segundos_ y la tercera vez con tres _terceros_. 
Si volviésemos a iterar `z` obtendríamos una excepción de la clase `StopIteration` porque ya no quedan mas objetos en el iterador. Después de iterar un iterador este queda vacío.

In [164]:
next(z)

StopIteration: 

* Habitualmente un iteardor se itera con un bucle `for`

In [40]:
l1 = ['C', 'Python', 'JavaScript'] 
l2 = "HOLA"
l3 = ['first', 'second', 'third', 'four']

for item in zip(l1, l2, l3):
    print(item)

('C', 'H', 'first')
('Python', 'O', 'second')
('JavaScript', 'L', 'third')


* A partir de un iterador podemos obtener una lista con la función `list()`

In [166]:
z =  zip(l1, l2, l3)  # creamos el iterador
l = list (z)          # creamos una lista apartir del iterador
print(l)

[('C', 17, 'first'), ('Python', 30, 'second'), ('JavaScript', 40, 'third')]


* En este ejemplo creamos el iterador con las secuencias devueltas por  `range(10)` y `range(100, 110)` , iteramos con el bucle for y utilizamos list comprenhesion

In [167]:
l = [x*y for x, y in zip(range(10), range(100, 110))]
l

[0, 101, 204, 309, 416, 525, 636, 749, 864, 981]

**Nunca** deberías utilizar el siguiente código (piensa por qué!!!)

In [168]:
# No utilizar
l = [x*y for x,y  in list(zip(range(10), range(100, 110)))]
l

[0, 101, 204, 309, 416, 525, 636, 749, 864, 981]

### Enumerate

* Recibe un objeto ordenable e iterable y devuelve una enumeración cuyos elementos son pares-objeto .  

In [19]:
grocery = ['bread', 'milk', 'butter']

# Creo un objeto de la clase enumarte a partir de la lista
enumerateGrocery = enumerate (grocery)

print(type(enumerateGrocery))

<class 'enumerate'>


In [170]:
# converting enumerate to list
print(list(enumerateGrocery))

[(0, 'bread'), (1, 'milk'), (2, 'butter')]


In [171]:
# changing the default counter
enumerateGrocery = enumerate(grocery, 10) #con dos parametros

print(list(enumerateGrocery))

[(10, 'bread'), (11, 'milk'), (12, 'butter')]


In [172]:
# Looping Over an Enumerate object
lc = [item for item in enumerate(grocery)]
print (lc)

[(0, 'bread'), (1, 'milk'), (2, 'butter')]


### Notación lambda para funciones

Cuando las funciones son de una sola linea, a menudo se definen por medio de la la notación `lambda`. En el siguiente ejemplo ambas definiciones de la función `square()`son equivalentes.  

In [24]:
def square(x):
    return x**2

square = lambda x: x**2

square(2)

4

## Tuplas

Las tuplas son muy similares a las listas. La diferencia es que las tuplas son objetos **no mutables**.

In [173]:
t =  ([1,2,3], 4, "hello world")
t

([1, 2, 3], 4, 'hello world')

* Podemos crear una tupla vacía, con un elemento, ...

In [8]:
t = () # t es una tupla vacía
t2 = tuple() # t2 también es una tupla vacía
t3 = ("hola", 2) # tupla con dos elementos


'''Para crear una tupla con uníco elemento, la coma es necesaria 
sino t4=(3) sería un enlace a un entero ''' 
t4 = (2,)   # t4 es una tupla con un elemento.  
t4

(2,)

**Ejemplo** Suponga la tupla `t = ([1,2,3], 4, "hello world")` ¿Sería posible modificar el primer elemento de la tupla? No, una tupla es un objeto no mutable. Si lo intentamos se lanzará una excepción `TypeError: 'tuple' object does not support item assignment'`.  Lo que sí podemos es modificar el contenido de la lista, incluso extraer todos sus elementos. 

In [17]:
t =  ([1,2,3], 4, "hello world")

t[0][0] = 5 # modifico un elemento de la lista
print (t)
t[0].pop()  # elimino un elemento de la lista
print(t)
t[0].clear() #elimino todos los elementos de la lista
print(t)

([5, 2, 3], 4, 'hello world')
([5, 2], 4, 'hello world')
([], 4, 'hello world')


## Diccionarios

* Crear y usar un diccionario es muy parecido a trabajar con una lista, excepto que ahora debe definir un **par de clave y valor**, `key:value`. Los elementos del diccionario son accedidos por claves **no** por índice (es decir, **los elementos de un diccionario no son indexables**)

In [174]:
empleado = {'nombre' : 'Eduardo', 'apellido' : 'Santos', 'edad' : 25}
empleado

{'nombre': 'Eduardo', 'apellido': 'Santos', 'edad': 25}

* La gran ventaja de esta estructura de datos es que los diccionarios pueden proporcionar rápidamente acceso a elementos de datos específicos utilizando la clave. 
Los diccionarios son la implementación Python de las tablas Hash. 

* Hay límites para los tipos de claves que se pueden utilizar. Las reglas especiales para crear una clave son:
 * La clave debe ser única. Cuando se ingresa una clave duplicada, la información que se encuentra en la segunda entrada reemplaza a la de la primera.
  * La clave puede ser cualquier objeto inmutable. Esta regla implica que se pueden usar cadenas, números o tuplas para la clave. Sin embargo, no puede usar una lista para una clave.

In [9]:
# claves duplicadas
registro = { 1:"Primer registro", 2:"Segundo registro", 2:"Tercer registro"}
print (registro)

# Diferentes tipos de claves
registro = { 1:"Primer registro", "Segundo registro":2, (1,2):"Primer registro y" + " Segundo registro" }
print(registro[1])
print(registro["Segundo registro"])
print(registro[(1,2)])

{1: 'Primer registro', 2: 'Tercer registro'}
Primer registro
2
Primer registro y Segundo registro


* Se pueden añadir elementos al diccionario mediante el método `update`o directamente

In [175]:
empleado.update ( {'estado_civil': 'soltero'})    # añade elemento con update
print (empleado)

empleado['profesion'] = 'soldador'                # añade elemento directamente
print (empleado)

{'nombre': 'Eduardo', 'apellido': 'Santos', 'edad': 25, 'estado_civil': 'soltero'}
{'nombre': 'Eduardo', 'apellido': 'Santos', 'edad': 25, 'estado_civil': 'soltero', 'profesion': 'soldador'}


* Se puede crear un dccionario vacío

In [46]:
d1 = {}  # diccionario vacío
d2 = dict()  #diccionario vacío
d2

{}

* El constructor `dic`devolverá un dict cuando reciba un iterable cuyos elementos sean pares llave-valor

In [47]:
t = ( ('cofee', 1.), ('sugar', 0.75) ) #tupla con pares de elementos
price = dict (t)
price

{'cofee': 1.0, 'sugar': 0.75}

* Podemos preguntar si una clave se encuentra en un diccionario

In [213]:
print ('salt' in price) 

False


* Los diccionarios son objetos iterables

In [179]:
for k in empleado:
    print (k)


nombre
apellido
edad
estado_civil
profesion


* Los diccionarios **no** son objetos indexables. Cuando se intenta acceder a los elementos de objeto_2 se lanza excepción. Verifica atentamente las diferencias entre los programas 

In [12]:
# codigo correcto
objeto_1 = {1:'lapiz', 2:'papel', 3:'tijera'}
for i in range(1, 4):
    print( objeto_1[i])

# código incorrecto
objeto_2 = {'uno':'lapiz', 'dos':'papel', 'tres':'tijera'}
for i in range(1, 4):
    print( objeto_2[i])

lapiz
papel
tijera


KeyError: 1

* **Error habitual** al crear un diccionario

In [52]:
d = { nombre:'Eduardo', apellido:'Serrano'}

NameError: name 'nombre' is not defined

## Algunos métodos

In [181]:
empleado.keys() #devuelve un objeto que muestra una lista no ordenada con las claves

dict_keys(['nombre', 'apellido', 'edad', 'estado_civil', 'profesion'])

In [182]:
empleado.values() # devuelve un objeto que muestra una lista con los valores del diccionario

dict_values(['Eduardo', 'Santos', 25, 'soltero', 'soldador'])

In [183]:
empleado.items()  #devuelve un objeto que muestra una lista de tuplas con clave-valor

dict_items([('nombre', 'Eduardo'), ('apellido', 'Santos'), ('edad', 25), ('estado_civil', 'soltero'), ('profesion', 'soldador')])

* **Dictionary comprenhesion**

**Ejercicio**: 
Suponga que tiene un diccionario con los precios en dólares de diferentes productos. Se desea crear un nuevo diccionario con los precios en euros

Podríamos haber resuelto el problema creando un nuevo diccionario y modificando sus valores con un bucle `for`

In [8]:
#item price in dollars
price_dollar = {'milk': 1.02, 'coffee': 2.5, 'bread': 2.5}
conversion = 0.99  # 1$ equivalent to 0.99€

#  Without using dictionary comprenhesion (non phytonic)
price_euro = dict (price_dollar)
for item, value in price_euro.items():
    price_euro[item] = value*conversion

print(price_euro)    

{'milk': 1.0098, 'coffee': 2.475, 'bread': 2.475}


Mas compacto utilizando *dictionary comprenhesion*

In [10]:
# Using dictionary comprenhesión
price_euro = { item : value*conversion for item, value in price_dollar.items() }
print (price_euro)

{'milk': 1.0098, 'coffee': 2.475, 'bread': 2.475}


**Ejercicio**
Convierte la lista `l = ["coffe",1.01, "milk", 2,3 ]` en un diccionario donde las claves sean los índices pares y las claves las impares  

In [5]:
l = ["coffe",1.01, "milk", 2,3 ]

#method 1, dictionary comprenhesion with iterable
d = { key:values for key, values in zip( l[::2], l[1::2])}
print(d)

#method 1b, A little worst
d = { l[i]:l[i+1] for i in range(0, len(l)-1, 2) }
print(d)

# method 2, using the dictionary constructor and a iterable
d = dict( zip( l[::2], l[1::2]) )
print (d)

{'coffe': 1.01, 'milk': 2}
{'coffe': 1.01, 'milk': 2}
{'coffe': 1.01, 'milk': 2}


# Conjuntos

# Funciones

* En Python una función se define utilizando la palabra clave `def`

In [185]:
def foo():
    print("Hello world")

def bar(x):
    return x+4

foo()
bar(5)

Hello world


9

* **Importante** En Python las funciones también son objetos. No confundir el *objeto* función con el *enlace* a una función tal y como se muestra en el  [siguiente ejemplo](https://pythontutor.com/visualize.html#code=def%20add%28%29%3A%0A%20%20%20%20c%20%3D%2010%0A%20%20%20%20print%28f'%20Esto%20esta%20c%20dentro%20de%20la%20funcion%20add%3A%20%7Bc%7D'%29%0A%20%20%20%20%0Adef%20add_2%28%29%3A%0A%20%20%20%20c%20%3D%2020%0A%20%20%20%20print%28f'%20Esto%20esta%20c%20dentro%20de%20add_2%3A%20%7Bc%7D'%29%0A%0Ac%20%3D%201%0Aadd%28%29%0Af%20%3D%20add%0Af%28%29%0A%0Aadd%20%3D%20add_2%0Aadd%28%29&cumulative=false&heapPrimitives=nevernest&mode=edit&origin=opt-frontend.js&py=3&rawInputLstJSON=%5B%5D&textReferences=false)

## Argumentos de funciones

* Al pasar valores a una función, Python usa las llamadas por **referencia a los objetos**.
    ¿Qué ocurre si le pasamos un objeto mutable a una función?:
    * Al pasarle una referencia al objeto, el objeto podría ser modificado dentro de la función con efectos fuera del ámbito de la función.
    * Sin embargo, si el enlace al objeto es re-enlazado dentro de la función, el ámbito externo no sabrá nada y no se realizarán cambios fuera del ámbito de la función.
    
Tenido en cuenta lo anterior, analiza detenidamente en el siguiente [código](https://pythontutor.com/render.html#code=%0Adef%20funcion_0%20%28ll,%20string%29%3A%0A%20%20%20%20ll%5B0%5D%20%3D%20string%0A%20%20%20%20return%20ll%0A%0Adef%20funcion_1%20%28ll,%20string%29%3A%0A%20%20%20%20ll%5B1%5D%20%3D%20string%0A%20%20%20%20return%20ll%0A%0A%0Adef%20funcion_2%20%28ll,%20string%29%3A%0A%20%20%20%20ll%20%3D%20%5B1,%202,%203%5D%0A%20%20%20%20ll%5B0%5D%20%3D%20string%0A%20%20%20%20return%20ll%0A%0A%0As%20%3D%20%22Hello%20world%22%0Al%20%3D%20%5B1,%202,%203%5D%0A%0Al_0%20%3D%20funcion_0%20%28l,%20s%29%0Al_1%20%3D%20funcion_1%20%28l,%20s%29%0Al_2%20%3D%20funcion_2%20%28l,%20%22bye%20bye%20world%22%29&cumulative=false&curInstr=21&heapPrimitives=nevernest&mode=display&origin=opt-frontend.js&py=3&rawInputLstJSON=%5B%5D&textReferences=false) en pythontutor, y observa los valores de la lista `l` tras las sucesivas llamadas

* Cuando se invoca a una función los valores que se pasan a la función se enlazan a los parámetros bien de forma posicional o mediante nombres formales de parámetros

In [54]:
def fun (nombre, apellido, asignatura, curso):
    print (f' El estudiante {nombre} {apellido} esta matriculado en {asignatura} de {curso}' )
    

# enlace posicional    
fun ('Eduardo', 'Lopez', 'AlgED', 2)  # nombre enlaza a 'Eduardo', apellido enlaza a 'Lopez', ....

# enlace utilizando los nombres formales de parametro
fun (apellido='Lopez', nombre='Eduardo', curso=2, asignatura='AlgED')

 El estudiante Eduardo Lopez esta matriculado en AlgED de 2
 El estudiante Eduardo Lopez esta matriculado en AlgED de 2


* En Python se pueden definir los argumentos de la función por clave (o con valores por defecto). 
    * Los argumentos posicionales deben preceder a los argumentos con clave. 
    * Si al invocar a la función se omite un argumento por clave, la función asignará al parámetro el valor por defecto.
    * Los valores por defecto se definen mediante `arg=value`

In [56]:
# funcion únicamente con argumentos posicionales
def fun_pos (nombre, apellido, asignatura, curso):
    print (f' El estudiante {nombre} {apellido} esta matriculado en {asignatura} de {curso}' )

# funcion con argumentos posicionales y argumentos por clave
def fun_clave (nombre, apellido, asignatura='AlgEd', curso=2):
    print (f' El estudiante {nombre} {apellido} esta matriculado en {asignatura} de {curso}' )

# Ejemplos de invocación de funciones
fun_pos ('Eduardo', 'Lopez', 'AlgED', 2) 
fun_clave ('Mengano', 'Serrano')
fun_clave ('Zutano', 'Mejias', curso=4, asignatura='Neuro')

 El estudiante Eduardo Lopez esta matriculado en AlgED de 2
 El estudiante Mengano Serrano esta matriculado en AlgEd de 2
 El estudiante Zutano Mejias esta matriculado en Neuro de 4


* Cuidado con los argumentos que tienen un valor por defecto cuando este sea un objeto mutable. Cuando se crea el objeto función en el *frame de los objetos*, se inicializan los argumentos por defecto. Si estos se modificasen cuando se invocase a la función, las modificaciones persisten entre llamadas sucesivas. Ejecuta el siguiente código en [pythontutor](https://pythontutor.com/render.html#code=%0Adef%20fun_peligrosa%20%28ele,%20l%20%3D%20%5B%5D%29%3A%0A%20%20%20%20l.append%20%28ele%29%0A%20%20%20%20print%28l%29%0A%20%20%20%20%0Adef%20fun_correcta%20%28ele,%20l%20%3D%20None%29%3A%0A%20%20%20%20if%20l%20%3D%3D%20None%3A%0A%20%20%20%20%20%20%20%20l%20%3D%20%5B%5D%0A%20%20%20%20l.append%20%28ele%29%0A%20%20%20%20print%20%28l%29%0A%0Afun_peligrosa%20%285%29%0Afun_peligrosa%20%2810%29%0A%0Afun_peligrosa%20%283,%20l%20%3D%20%5B1,1%5D%29%0Afun_peligrosa%20%285%29%0A%0Afun_correcta%20%285%29%0Afun_correcta%20%2810%29&cumulative=false&curInstr=0&heapPrimitives=nevernest&mode=display&origin=opt-frontend.js&py=3&rawInputLstJSON=%5B%5D&textReferences=false)

 * En la función `fun_peligrosa()` El argumento l tiene como valor por defecto una lista vacía. En la llamada a `fun_peligrosa (5)` como no se le ha pasado una lista el elemento 5 se añade a la lista *por defecto* l. Si ahora volvemos a invocar a fun_peligrosa **sin** el argumento por defecto, e.g.,  `fun_peligrosa(10)` el valor 10 se añade a la lista *por defecto* cuyo primer elemento era el 5. 
 * Compara la implementación de fun_peligrosa con la de fun_correcta.


In [ ]:

def fun_peligrosa (ele, l = []):
    l.append (ele)
    print(l)
    
def fun_correcta (ele, l = None):
    if l == None:
        l = []
    l.append (ele)
    print (l)

fun_peligrosa (5)
fun_peligrosa (10)

fun_peligrosa (3, l = [1,1])
fun_peligrosa (5)

fun_correcta (5)
fun_correcta (10)

* Cuando se llama a una función los argumentos posicionales se empaquetan en una `tupla` (args) mientras que los argumentos por defecto se empaquetan en un `dict` (kwargs) con los nombres de las variables como claves y los valores por defecto como valores del diccionario. Por ejemplo, en la función `fun_clave()`, `args = (nombre, apellido)` y `kwargs = {'asignatura':AlgED', 'curso':2}`

## Funciones como argumento de funciones

In [198]:
def square (x):
    return x**2

def list_values (x, f):
    return [f(i) for i in range(x)]


l = list_values (20, square)
print (l)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361]


## Retorno de funciones

* En Python las funciones o bien no devuelven nada, `None`, o bien devuelven **una única** tupla de valores. En el siguiente ejemplo el objeto devuelto por la función `fun()` es una tupla con tres valores (**no** devuelve tres valores).

In [188]:
def fun():
    x, y, z = 1, 2, 3
    return x, y, z

l = fun()
print(l)
type(l)

(1, 2, 3)


tuple

## Variables globales y funciones [ref](https://www.programiz.com/python-programming/global-keyword)

* In Python, global keyword allows you to modify the variable outside of the current scope. It is used to create a global variable and make changes to the variable in a local context.

* Rules of global Keyword
   * When we define a variable outside of a function, it is global by default. You don't have to use global keyword.
   * When we create a variable inside a function, it is local by default.
   * We use global keyword to read and write a global variable inside a function.
   * Use of global keyword outside a function has no effect.

Ejemplo de variable global [ejemplo_1](https://pythontutor.com/render.html#code=c%20%3D%201%20%23%20global%20variable%0A%0Adef%20add%28%29%3A%0A%20%20%20%20print%28f'%20Esto%20esta%20c%20dentro%20de%20la%20funcion%20add%3A%20%7Bc%7D'%29%0A%20%20%20%20%0Adef%20add_2%28%29%3A%0A%20%20%20%20print%28f'%20Esto%20esta%20c%20dentro%20de%20add_2%3A%20%7Bc%7D'%29%0A%0Aadd%28%29%0Af%20%3D%20add%0Af%28%29%0A%0Aadd%20%3D%20add_2%0Aadd%28%29&cumulative=false&curInstr=17&heapPrimitives=nevernest&mode=display&origin=opt-frontend.js&py=3&rawInputLstJSON=%5B%5D&textReferences=false)

Sin embargo la siguiente función es incorrecta. Cuando se ejecuta se lanza una excepción de la clase `UnboundLocalError` Es importante que entiendas el mensaje de error!! 


In [189]:
c = 1 # global variable
    
def add():
    c = c + 2 # try to increment c by 2
    print(c)

add()

UnboundLocalError: local variable 'c' referenced before assignment

En el código anterior se debería haber definido c como una variable global

In [190]:
c = 1 # global variable

def add():
    global c
    c = c + 2 # increment by 2
    print("Inside add():", c)

add()
print(f'In main: {c}')

Inside add(): 3
In main: 3


* Variable global en una función anidada [example](https://pythontutor.com/render.html#code=def%20foo%28%29%3A%0A%20%20%20%20x%20%3D%2020%0A%0A%20%20%20%20def%20bar%28%29%3A%0A%20%20%20%20%20%20%20%20global%20x%0A%20%20%20%20%20%20%20%20x%20%3D%20x%20%2B%203%0A%20%20%20%20%0A%20%20%20%20print%28f%22Before%20calling%20bar%3A%20%7Bx%7D%22%29%0A%20%20%20%20print%28%22Calling%20bar%20now%22%29%0A%20%20%20%20bar%28%29%0A%20%20%20%20print%28f%22After%20calling%20bar%3A%20%7Bx%7D%22%29%0A%0A%0Ax%20%3D%2010%0Aprint%28f%22x%20in%20main%3A%20%7Bx%7D%22%29%0Afoo%28%29%0Aprint%28f%22x%20in%20main%3A%20%7Bx%7D%22%29&cumulative=false&curInstr=16&heapPrimitives=nevernest&mode=display&origin=opt-frontend.js&py=3&rawInputLstJSON=%5B%5D&textReferences=false)

## Argumentos *args* y *kwargs*

### En la invocación de una función

* En el siguiente ejemplo la función `fun()` tiene tres argumentos.  Podemos invocarla pasándole la lista `args`en la que, previamente, hemos desempaquetado sus elementos con `*`  

In [191]:
def fun(x, y, oper):
    ''' Funcion de tres argumentos'''
    if oper == '+':
        return x+y
    else:
        return x*y
        
args = (1, 2, '*')
fun (*args)  # equivalente a ejecutar: fun (args[0], args[1], args[2])

2

* La siguiente función tiene dos argumentos posicionales (`x`e `y`) y uno por defecto (`tipo`). Podemos invocara a la función con una tupla que desempaquetamos para asignar valor a los argumentos posicionales y un diccionario que, a su vez, desempaquetamos para asignar los argumentos con clave. 

In [57]:
def fun (x, y, tipo = 'triangulo'):
    if tipo == 'triangulo':
        return x*y/2
    else:
        return x*y

args = (4,2)
kwargs = { 'tipo' : "rectangulo"}
fun(*args, **kwargs) # equivalente a ejecutar: fun (args[0], args[1], tipo="rectangulo")

8

* La función anterior también podemos invocarla usando únicamente un diccionario que desempaquetamos

In [193]:
kwargs = {'y':2, 'x':4,  'tipo' : "rectangulo"}
fun(**kwargs) # equivalente a ejecutar: fun (args[0], args[1], "rectangulo")

8

o una única tupla

In [194]:
kwargs = (4, 2, "rectangulo")
fun (*args)

4.0

### En la definición de la función

* Podemos definir una función con un número arbitrario de parámetros posicionales mediante el uso de `args`. En el ejemplo, la variable args se enlaza a una tupla tal y como puedes observar en  [pythontutor](https://pythontutor.com/render.html#code=def%20add_arg_var%20%28*args%29%3A%0A%20%20%20%20value%20%3D%200%0A%20%20%20%20for%20i%20in%20args%3A%0A%20%20%20%20%20%20%20%20value%20%2B%3D%20i%0A%20%20%20%20print%20%28value%29%0A%20%20%20%20%0A%0Aadd_arg_var%20%283,4,5%29%0Aadd_arg_var%20%283,4,5,6%29&cumulative=false&curInstr=15&heapPrimitives=nevernest&mode=display&origin=opt-frontend.js&py=3&rawInputLstJSON=%5B%5D&textReferences=false)

In [58]:
def add_arg_var (*args):
    value = 0
    for i in args:  #se itera la tupla args
        value += i
    print (value)
    

add_arg_var (3,4,5)
add_arg_var (3,4,5,6)

12
18


* Igualmente con `**kwargs` podemos definir una función con un número arbitrario de parámetros con clave. En el siguiente ejemplo cuando se invoca a la función se enlaza `kwargs` con el dict {'base'=2, 'altura'=4} tal y como puedes comprobar en [pythontutor](https://pythontutor.com/render.html#code=def%20fun%28**kwargs%29%3A%0A%20%20%20%20for%20key,%20values%20in%20kwargs.items%28%29%3A%0A%20%20%20%20%20%20%20%20print%20%28key,%20values%29%0A%0Afun%20%28base%3D2,%20altura%3D4%29&cumulative=false&curInstr=2&heapPrimitives=nevernest&mode=display&origin=opt-frontend.js&py=3&rawInputLstJSON=%5B%5D&textReferences=false) 

In [196]:
def fun(**kwargs):
    for key, values in kwargs.items():
        print (key, values)

fun (base=2, altura=4)

base 2
altura 4


**Ejemplo** En este ejemplo se utiliza kwargs tanto en la definición de la función `operacion`como en la llamada. En el ejemplo la función `operacion` necesita pasar diferentes argumentos según se invoque a la función `potencia`o a `logaritmo`[pythontutor](https://pythontutor.com/render.html#code=import%20math%0A%0Adef%20potencia%20%28x,%20exponente%3D2%29%3A%0A%20%20%20%20return%20x**exponente%0A%20%20%20%20%0Adef%20logaritmo%20%28x,%20base%3D10%29%3A%0A%20%20%20%20return%20math.log%28x,%20base%29%0A%0Adef%20operacion%20%28x,%20f,%20**kwargs%29%3A%20%20%23%20en%20la%20definici%C3%B3n%20de%20la%20funci%C3%B3n%0A%20%20%20%20return%20f%28x,%20**kwargs%29%20%20%20%20%20%20%20%20%23%20en%20%0A%0A%20%20%20%20%0A%0Aprint%20%28%20operacion%20%2810,%20potencia,%20exponente%20%3D%203%29%20%29%0Aprint%20%28%20operacion%20%2810,%20logaritmo,%20base%20%3D%2010%29%20%29&cumulative=false&curInstr=12&heapPrimitives=nevernest&mode=display&origin=opt-frontend.js&py=3&rawInputLstJSON=%5B%5D&textReferences=false). 

In [6]:
import math

def potencia (x, exponente=2):
    return x**exponente
    
def logaritmo (x, base=10):
    return math.log(x, base)

def square (x):
    return x**2

def operacion (x, f, **kwargs):  # en la definición de la función
    ''' Version 1'''
    return f(x, **kwargs)        # en la invocacion tiene que pasarse los argumentos desempaquetados

# Drive code
print ( operacion (x=10, f=potencia, exponente = 3) )
print ( operacion (x=10, f=logaritmo, base = 10) )
print ( operacion (x=10, f=square) )



1000
1.0
100


* La función `operacion()` podríamos programarla de otra forma. En este caso `operacion()` tiene un argumento con clave `param` cuyo valor por defecto es una lista vacía. Cuando `operacion()` invoca a `f` desempaqueta la tupla `param`   

In [16]:
def operacion (x, f, param=tuple()):
    ''' Version 2 de la función operacion '''
    return f(x, *param)


# Drive code
print ( operacion (x=10, f=potencia, param=(3,) ) )
print ( operacion (x=10, f=logaritmo, param=(2,) ) )
print ( operacion (x=10, f=square) )


1000
3.3219280948873626
100


## Anotación de funciones

Anotar tus funciones mejorará mucho la legibilidad de tu código. En la siguiente página se muestran varios ejemplos
[anotación funciones](https://towardsdatascience.com/12-beginner-concepts-about-type-hints-to-improve-your-python-code-90f1ba0ac49)


# Módulos

* Son ficheros _*.py_ que contienen sentencias, definición de funciones, variables globales, etc

* La sentencia `import` enlaza un módulo con el ámbito donde ocurre el import

* Si el fichero *my_module.py* ha sido modificado después del `import`, tiene que ser recargado para actualizar los enlaces previos: `reload (mm)`. La función reload realiza una comprobación sintáctica

* Se accede a las funciones (o variables) del módulo mediante notación de objetos (.): mm.funcname ( ... )



In [59]:
%%bash  

ls -lht test*
cat test.py

-rw-rw-r-- 1 eduardo eduardo 61 sep 13 02:24 test.py


def fun (x):
	print ("Hello " + x + " congratulations")





In [3]:
import test            # importo el modulo test.py 

test.fun ('Eduardo')   # se invoca a la funcion fun() del modulo 

Hello Eduardo


In [6]:
import importlib

importlib.reload (test)

test.fun('Pepe')

Hello Pepe congratulations


* Algunos módulos útiles

|Módulo |	Operation	|
|-------- | ------------| 
| os, sys |  para tareas relacionadas con el sistema operativo |
| math | para operaciones matemáticas estándar|
| matplotlib | para dibujar gráficas (lo veremos más adelante) |
|numpy | para álgebra lineal (lo veremos más adelante) |
| scipy | para cálculo científico |
| pandas | para cálculo con tablas (lo veremos más adelante) |
| sklearn | para aprendizaje automático (lo veremos más adelante) |
|statsmodels | para estadística|

## Numpy

### Arrays


* Supongamos que deseamos hacer ciertos cálculos algebraicos y necesitamos utilizar vectores y matrices. ¿Como podemos implementarlas en Python? 
    * Podemos utilizar listas 
    * Mucho mejor: con Arrays, objetos definidos en el módulo Numpy  

In [5]:
# Utilizando listas
v = [1,2,3] 
m = [ [1,2,3], [4,5,6], [7,8,9]]

In [3]:
import numpy as np

a = np.array ([1,2,3])   #conversion de lista en array
b = np.array ( [[1,2,3], [14,5,6], [27,8,9]] )

print(a)
print(b)

[1 2 3]
[[ 1  2  3]
 [14  5  6]
 [27  8  9]]


In [7]:
np.shape (m) # Return the shape (dimension) of the numpy object. Equivalent to variable: m.shape

(3, 3)

* Los arrays se pueden indexar y trocear

In [ ]:
a[1,1]
a[0, ] # Primera fila
a[0, 1:3] 

* Dado un array se pueden modificar sus dimensiones

In [ ]:
c = np.arange(6) # Equivalente a la funcion range() pero devuelve un array
c.reshape(3,2)

In [25]:
c.reshape(2, -1) # Con -1 la segunda dimensión se ajusta para que sea compatible

array([[0, 1, 2],
       [3, 4, 5]])

**Métodos de array**

In [17]:
m = np.empty ((3,3))     # Return a new array of given shape without initializing entries (3,3)
m = np.zeros ((5, 5))    # una matriz cuadrada 5 x 5 llena de ceros
m = np.eye(5)            # matriz identidad de 5 x 5

c = a + b                # suma elemento a elemento
c= a * b                 # multiplicación elemento a elemento
c = a.dot(b)             # multiplication de dos arrays
m = np.eye(5)            # matriz identidad de 5 x 5
a / 5.                   # división elemento a elemento
l = np.array(a)  #conversión de lista en array
a.T                      # traspuesta
np.linalg.det(m)    # determinante

1.0

**Algunas funciones**

In [18]:
a = np.random.randint (0, high=11, size= (4,4)) #Return random integers from low (inclusive) to high (exclusive).
print(a)

print( a.mean(axis=0) )     # media de las columnas de a
print( a.mean(axis=1) )
a.mean()                    # media de todos los elementos del array

[[6 9 2 4]
 [2 2 6 8]
 [0 6 0 3]
 [2 0 8 9]]
[2.5  4.25 4.   6.  ]
[5.25 4.5  2.25 4.75]


4.1875

* En numpy todas sus funciones están paralelizadas

* Cuidado con la gestion de memoria y las subsecuencias en numpy. A diferencia de una lista donde al acceder a una sub-secuencia de una lista se "crea una copia" de la lista original, un sub-array de un array de numpy es una vista!! Esto tiene importantes consecuencias en como debemos gestionar la memoria cuando trabajamos con grandes cantidades de datos. [Echa un vistazo a esta referencia](https://pythonspeed.com/articles/numpy-memory-views/)

In [10]:
# Cuidado con las sub-secuencias. Una subsecuencia crea una copia

x = [900, 800, 700]
l_o = ["hola", "pepe", 3, 4, x]

l_c = l_o[1:]

x[0] = 999
print (f'l_o: {l_o}, l_c:{l_c}')

l_o[-1] = "cambio"
print (f'l_o: {l_o}, l_c:{l_c}')

# Y si fuesen numpy arrays ?

a_o = np.array ([[1,2,3],[4,5,6]])
a_c = a_o[0, :]

print(f'a_o: {a_o} \na_c: {a_c}')

#modifico el array 
a_o[0,] =[11,22,33]
print(f'a_o: {a_o} \na_c: {a_c}')


l_o: ['hola', 'pepe', 3, 4, [999, 800, 700]], l_c:['pepe', 3, 4, [999, 800, 700]]
l_o: ['hola', 'pepe', 3, 4, 'cambio'], l_c:['pepe', 3, 4, [999, 800, 700]]
a_o: [[1 2 3]
 [4 5 6]] 
a_c: [1 2 3]
a_o: [[11 22 33]
 [ 4  5  6]] 
a_c: [11 22 33]
